name: Generate craftcms-v5
on:
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Checkout craftcms/cms repository
        uses: actions/checkout@v4
        with:
          repository: craftcms/cms
          ref: 5.x
          path: source

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Repomix
        run: npm install -g repomix

      - name: Pack repository with Repomix
        run: repomix source --output craftcms-v5.xml

      - name: Commit file
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add craftcms-v5.xml
          git commit -m "Update craftcms-v5.xml"
          git push
